import type { UserRole } from "@prisma/client";

export type Permission =
  | "PROJECT_READ_OWN"
  | "PROJECT_CREATE"
  | "PROJECT_UPDATE_OWN"
  | "PROJECT_READ_ALL"
  | "PROJECT_ASSIGN"
  | "QUOTE_CREATE"
  | "QUOTE_APPROVE"
  | "PAYMENT_READ"
  | "PAYMENT_CONFIRM"
  | "TECHNICIAN_JOB_READ"
  | "TECHNICIAN_JOB_UPDATE"
  | "ADMIN_USER_MANAGE"
  | "AUDIT_READ";

export const MEDIA_STAFF_ROLES: readonly UserRole[] = [
  "SUPER_ADMIN", "ADMIN", "OPERATIONS", "TECHNICIAN"
];

export const MEDIA_DELETE_ROLES: readonly UserRole[] = [
  "SUPER_ADMIN", "ADMIN", "OPERATIONS"
];

const permissions: Record<UserRole, readonly Permission[]> = {
  CUSTOMER: ["PROJECT_READ_OWN", "PROJECT_CREATE", "PROJECT_UPDATE_OWN"],
  SUPER_ADMIN: [
    "PROJECT_READ_ALL", "PROJECT_ASSIGN", "QUOTE_CREATE", "QUOTE_APPROVE",
    "PAYMENT_READ", "PAYMENT_CONFIRM", "TECHNICIAN_JOB_READ",
    "TECHNICIAN_JOB_UPDATE", "ADMIN_USER_MANAGE", "AUDIT_READ"
  ],
  ADMIN: [
    "PROJECT_READ_ALL", "PROJECT_ASSIGN", "QUOTE_CREATE", "QUOTE_APPROVE",
    "PAYMENT_READ", "TECHNICIAN_JOB_READ", "TECHNICIAN_JOB_UPDATE", "AUDIT_READ"
  ],
  SALES: ["PROJECT_READ_ALL", "QUOTE_CREATE"],
  ESTIMATOR: ["PROJECT_READ_ALL", "QUOTE_CREATE"],
  ACCOUNTS: ["PROJECT_READ_ALL", "PAYMENT_READ", "PAYMENT_CONFIRM"],
  OPERATIONS: ["PROJECT_READ_ALL", "PROJECT_ASSIGN", "TECHNICIAN_JOB_READ", "TECHNICIAN_JOB_UPDATE"],
  TECHNICIAN: ["TECHNICIAN_JOB_READ", "TECHNICIAN_JOB_UPDATE"]
};

export function hasPermission(role: UserRole, permission: Permission) {
  return permissions[role].includes(permission);
}
